start Notepad++ index.html
start Notepad++ README.md
start Notepad++ css/game-show-fusion.css
start Notepad++ js/game-show-fusion.js
start Notepad++ todo-list.txt
start Notepad++ unit-tests.html
start Notepad++ js/unit-tests.js
start Notepad++ js/game-controller.js
start Notepad++ js/game-controller.js
start Notepad++ js/canvas-stack.js
start Notepad++ js/error-handling.js
start Notepad++ js/utility.js
start Notepad++ js/money-display.js
start Notepad++ js/briefcase-display.js
start Notepad++ js/key-actions.js
start Notepad++ js/key-action.js
start Notepad++ js/canvas-ids.js
start Notepad++ js/explain-rules.js
start Notepad++ js/speaker.js
start Notepad++ js/question.js
start Notepad++ js/subjects.js
start Notepad++ js/questions.js
start Notepad++ js/grades.js
exit